// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35)
const floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35_transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35.addComponentOrReplace(floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35_transform)
const floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35_GLTFShape = new GLTFShape("assets/models/c9b17021-765c-4d9a-9966-ce93a9c323d1/FloorBaseGrass_01/FloorBaseGrass_01.glb")
floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35_GLTFShape.withCollisions = true
floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35_GLTFShape.isPointerBlocker = true
floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35_GLTFShape.visible = true
floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35.addComponentOrReplace(floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const construction_426309a2e66647e4a1772df96632f90b = new Entity("Construction")
engine.addEntity(construction_426309a2e66647e4a1772df96632f90b)
const construction_426309a2e66647e4a1772df96632f90b_transform = new Transform({
  position: new Vector3(24, 0, 24.25),
  rotation: new Quaternion(0, 1, 0, 1.341104E-07),
  scale: new Vector3(1, 1, 1)
})
construction_426309a2e66647e4a1772df96632f90b.addComponentOrReplace(construction_426309a2e66647e4a1772df96632f90b_transform)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionCone01_51992f1bdb4d4330b779229281a8ecba = new Entity("Construction Cone 01")
engine.addEntity(constructionCone01_51992f1bdb4d4330b779229281a8ecba)
const constructionCone01_51992f1bdb4d4330b779229281a8ecba_transform = new Transform({
  position: new Vector3(-4.298, 0, -6.450999),
  rotation: new Quaternion(0, 0.4257793, 0, 0.9048271),
  scale: new Vector3(1, 1, 1)
})
constructionCone01_51992f1bdb4d4330b779229281a8ecba.addComponentOrReplace(constructionCone01_51992f1bdb4d4330b779229281a8ecba_transform)
const constructionCone01_51992f1bdb4d4330b779229281a8ecba_GLTFShape = new GLTFShape("assets/models/250aff0f-bfc5-4a40-a163-72dca28606cb/ConstructionCone_01/ConstructionCone_01.glb")
constructionCone01_51992f1bdb4d4330b779229281a8ecba_GLTFShape.withCollisions = true
constructionCone01_51992f1bdb4d4330b779229281a8ecba_GLTFShape.isPointerBlocker = true
constructionCone01_51992f1bdb4d4330b779229281a8ecba_GLTFShape.visible = true
constructionCone01_51992f1bdb4d4330b779229281a8ecba.addComponentOrReplace(constructionCone01_51992f1bdb4d4330b779229281a8ecba_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionSign01_c89e62cf50de4a7daa56695c46877c70 = new Entity("Construction Sign 01")
engine.addEntity(constructionSign01_c89e62cf50de4a7daa56695c46877c70)
const constructionSign01_c89e62cf50de4a7daa56695c46877c70_transform = new Transform({
  position: new Vector3(-6.727001, 0, -4.667),
  rotation: new Quaternion(0, 0.922201, 0, 0.386711),
  scale: new Vector3(1, 1, 1)
})
constructionSign01_c89e62cf50de4a7daa56695c46877c70.addComponentOrReplace(constructionSign01_c89e62cf50de4a7daa56695c46877c70_transform)
const constructionSign01_c89e62cf50de4a7daa56695c46877c70_GLTFShape = new GLTFShape("assets/models/552e9281-df22-462d-9125-3c66853505d0/ConstructionSign_01/ConstructionSign_01.glb")
constructionSign01_c89e62cf50de4a7daa56695c46877c70_GLTFShape.withCollisions = true
constructionSign01_c89e62cf50de4a7daa56695c46877c70_GLTFShape.isPointerBlocker = true
constructionSign01_c89e62cf50de4a7daa56695c46877c70_GLTFShape.visible = true
constructionSign01_c89e62cf50de4a7daa56695c46877c70.addComponentOrReplace(constructionSign01_c89e62cf50de4a7daa56695c46877c70_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionFence01_61a8d02b76914237b9f68254ba07ff2a = new Entity("Construction Fence 01")
engine.addEntity(constructionFence01_61a8d02b76914237b9f68254ba07ff2a)
const constructionFence01_61a8d02b76914237b9f68254ba07ff2a_transform = new Transform({
  position: new Vector3(-6.741001, 0, 0.307001),
  rotation: new Quaternion(0, 0.08019901, 0, -0.9967789),
  scale: new Vector3(1, 1, 1)
})
constructionFence01_61a8d02b76914237b9f68254ba07ff2a.addComponentOrReplace(constructionFence01_61a8d02b76914237b9f68254ba07ff2a_transform)
const constructionFence01_61a8d02b76914237b9f68254ba07ff2a_GLTFShape = new GLTFShape("assets/models/03635caa-b836-446a-9797-4850f1f668df/ConstructionFence_01/ConstructionFence_01.glb")
constructionFence01_61a8d02b76914237b9f68254ba07ff2a_GLTFShape.withCollisions = true
constructionFence01_61a8d02b76914237b9f68254ba07ff2a_GLTFShape.isPointerBlocker = true
constructionFence01_61a8d02b76914237b9f68254ba07ff2a_GLTFShape.visible = true
constructionFence01_61a8d02b76914237b9f68254ba07ff2a.addComponentOrReplace(constructionFence01_61a8d02b76914237b9f68254ba07ff2a_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionFence01_d395dc5ade504db8bcdec9c5f94e7166 = new Entity("Construction Fence 01")
engine.addEntity(constructionFence01_d395dc5ade504db8bcdec9c5f94e7166)
const constructionFence01_d395dc5ade504db8bcdec9c5f94e7166_transform = new Transform({
  position: new Vector3(-6.346999, 0, 3.633001),
  rotation: new Quaternion(0, 0.07671884, 0, -0.9970528),
  scale: new Vector3(1, 1, 1)
})
constructionFence01_d395dc5ade504db8bcdec9c5f94e7166.addComponentOrReplace(constructionFence01_d395dc5ade504db8bcdec9c5f94e7166_transform)
constructionFence01_d395dc5ade504db8bcdec9c5f94e7166.addComponentOrReplace(constructionFence01_61a8d02b76914237b9f68254ba07ff2a_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionCone01_9934600b25754a92a1d38ba1d3dc3386 = new Entity("Construction Cone 01")
engine.addEntity(constructionCone01_9934600b25754a92a1d38ba1d3dc3386)
const constructionCone01_9934600b25754a92a1d38ba1d3dc3386_transform = new Transform({
  position: new Vector3(-5.330999, 0, -6.521),
  rotation: new Quaternion(0, 0.3842955, 0, -0.9232101),
  scale: new Vector3(1, 1, 1)
})
constructionCone01_9934600b25754a92a1d38ba1d3dc3386.addComponentOrReplace(constructionCone01_9934600b25754a92a1d38ba1d3dc3386_transform)
constructionCone01_9934600b25754a92a1d38ba1d3dc3386.addComponentOrReplace(constructionCone01_51992f1bdb4d4330b779229281a8ecba_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionFence01_d4a8387efdb6472483543df8dfbb092b = new Entity("Construction Fence 01")
engine.addEntity(constructionFence01_d4a8387efdb6472483543df8dfbb092b)
const constructionFence01_d4a8387efdb6472483543df8dfbb092b_transform = new Transform({
  position: new Vector3(4.109999, 0, -6.855),
  rotation: new Quaternion(0, 0.7477981, 0, 0.6639262),
  scale: new Vector3(1, 1, 1)
})
constructionFence01_d4a8387efdb6472483543df8dfbb092b.addComponentOrReplace(constructionFence01_d4a8387efdb6472483543df8dfbb092b_transform)
constructionFence01_d4a8387efdb6472483543df8dfbb092b.addComponentOrReplace(constructionFence01_61a8d02b76914237b9f68254ba07ff2a_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionFence01_95a6c3c57ca04fd38c1da67c4cd4e247 = new Entity("Construction Fence 01")
engine.addEntity(constructionFence01_95a6c3c57ca04fd38c1da67c4cd4e247)
const constructionFence01_95a6c3c57ca04fd38c1da67c4cd4e247_transform = new Transform({
  position: new Vector3(-2.75, 0, -6.749999),
  rotation: new Quaternion(0, 0.763796, 0, 0.6454577),
  scale: new Vector3(1, 1, 1)
})
constructionFence01_95a6c3c57ca04fd38c1da67c4cd4e247.addComponentOrReplace(constructionFence01_95a6c3c57ca04fd38c1da67c4cd4e247_transform)
constructionFence01_95a6c3c57ca04fd38c1da67c4cd4e247.addComponentOrReplace(constructionFence01_61a8d02b76914237b9f68254ba07ff2a_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionFence01_262d328e8cd7437c99bfc1f825482e64 = new Entity("Construction Fence 01")
engine.addEntity(constructionFence01_262d328e8cd7437c99bfc1f825482e64)
const constructionFence01_262d328e8cd7437c99bfc1f825482e64_transform = new Transform({
  position: new Vector3(0.6200009, 0, -6.890999),
  rotation: new Quaternion(0, 0.6794413, 0, 0.7337299),
  scale: new Vector3(1, 1, 1)
})
constructionFence01_262d328e8cd7437c99bfc1f825482e64.addComponentOrReplace(constructionFence01_262d328e8cd7437c99bfc1f825482e64_transform)
constructionFence01_262d328e8cd7437c99bfc1f825482e64.addComponentOrReplace(constructionFence01_61a8d02b76914237b9f68254ba07ff2a_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionFence01_e3b5a4cc484a4eb380ab6d0eae30c55f = new Entity("Construction Fence 01")
engine.addEntity(constructionFence01_e3b5a4cc484a4eb380ab6d0eae30c55f)
const constructionFence01_e3b5a4cc484a4eb380ab6d0eae30c55f_transform = new Transform({
  position: new Vector3(-6.405999, 0, -2.74),
  rotation: new Quaternion(0, 0.02443218, 0, 0.9997015),
  scale: new Vector3(1, 1, 1)
})
constructionFence01_e3b5a4cc484a4eb380ab6d0eae30c55f.addComponentOrReplace(constructionFence01_e3b5a4cc484a4eb380ab6d0eae30c55f_transform)
constructionFence01_e3b5a4cc484a4eb380ab6d0eae30c55f.addComponentOrReplace(constructionFence01_61a8d02b76914237b9f68254ba07ff2a_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionCone01_baac1c63b2864256ae7214e96b2ac1d8 = new Entity("Construction Cone 01")
engine.addEntity(constructionCone01_baac1c63b2864256ae7214e96b2ac1d8)
const constructionCone01_baac1c63b2864256ae7214e96b2ac1d8_transform = new Transform({
  position: new Vector3(-6.5, 0, -4.75),
  rotation: new Quaternion(0, 0.2419219, 0, 0.9702957),
  scale: new Vector3(1, 1, 1)
})
constructionCone01_baac1c63b2864256ae7214e96b2ac1d8.addComponentOrReplace(constructionCone01_baac1c63b2864256ae7214e96b2ac1d8_transform)
constructionCone01_baac1c63b2864256ae7214e96b2ac1d8.addComponentOrReplace(constructionCone01_51992f1bdb4d4330b779229281a8ecba_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionLadder01_707ba14ce5c34c65b6b49a182563223f = new Entity("Construction Ladder 01")
engine.addEntity(constructionLadder01_707ba14ce5c34c65b6b49a182563223f)
const constructionLadder01_707ba14ce5c34c65b6b49a182563223f_transform = new Transform({
  position: new Vector3(-6.5, 0, -6.75),
  rotation: new Quaternion(0, 0.258819, 0, 0.9659259),
  scale: new Vector3(1, 1, 1)
})
constructionLadder01_707ba14ce5c34c65b6b49a182563223f.addComponentOrReplace(constructionLadder01_707ba14ce5c34c65b6b49a182563223f_transform)
const constructionLadder01_707ba14ce5c34c65b6b49a182563223f_GLTFShape = new GLTFShape("assets/models/32a90a74-dec8-49ae-8a5c-ecedaa0cd744/ConstructionLadder_01/ConstructionLadder_01.glb")
constructionLadder01_707ba14ce5c34c65b6b49a182563223f_GLTFShape.withCollisions = true
constructionLadder01_707ba14ce5c34c65b6b49a182563223f_GLTFShape.isPointerBlocker = true
constructionLadder01_707ba14ce5c34c65b6b49a182563223f_GLTFShape.visible = true
constructionLadder01_707ba14ce5c34c65b6b49a182563223f.addComponentOrReplace(constructionLadder01_707ba14ce5c34c65b6b49a182563223f_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const constructionCone01_2baadfe09cac4f1d9349b272343af786 = new Entity("Construction Cone 01")
engine.addEntity(constructionCone01_2baadfe09cac4f1d9349b272343af786)
const constructionCone01_2baadfe09cac4f1d9349b272343af786_transform = new Transform({
  position: new Vector3(-6.298999, 0, -5.966),
  rotation: new Quaternion(0, 0.2520694, 0, -0.9677092),
  scale: new Vector3(1, 1, 1)
})
constructionCone01_2baadfe09cac4f1d9349b272343af786.addComponentOrReplace(constructionCone01_2baadfe09cac4f1d9349b272343af786_transform)
constructionCone01_2baadfe09cac4f1d9349b272343af786.addComponentOrReplace(constructionCone01_51992f1bdb4d4330b779229281a8ecba_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass01_06f40b9334dd442da03257be27c49f05 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass01_06f40b9334dd442da03257be27c49f05)
const floorBaseGrass01_06f40b9334dd442da03257be27c49f05_transform = new Transform({
  position: new Vector3(8, 0, 24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass01_06f40b9334dd442da03257be27c49f05.addComponentOrReplace(floorBaseGrass01_06f40b9334dd442da03257be27c49f05_transform)
floorBaseGrass01_06f40b9334dd442da03257be27c49f05.addComponentOrReplace(floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass01_c5ae32d19c3c4a22901dc661c4bde6e7 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass01_c5ae32d19c3c4a22901dc661c4bde6e7)
const floorBaseGrass01_c5ae32d19c3c4a22901dc661c4bde6e7_transform = new Transform({
  position: new Vector3(24, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass01_c5ae32d19c3c4a22901dc661c4bde6e7.addComponentOrReplace(floorBaseGrass01_c5ae32d19c3c4a22901dc661c4bde6e7_transform)
floorBaseGrass01_c5ae32d19c3c4a22901dc661c4bde6e7.addComponentOrReplace(floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass01_ff324faa9bf74ca3a737862e4829c2fc = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass01_ff324faa9bf74ca3a737862e4829c2fc)
const floorBaseGrass01_ff324faa9bf74ca3a737862e4829c2fc_transform = new Transform({
  position: new Vector3(24, 0, 24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass01_ff324faa9bf74ca3a737862e4829c2fc.addComponentOrReplace(floorBaseGrass01_ff324faa9bf74ca3a737862e4829c2fc_transform)
floorBaseGrass01_ff324faa9bf74ca3a737862e4829c2fc.addComponentOrReplace(floorBaseGrass01_2ddfdf6bc782478baacee7279a29aa35_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity_624a0f83cd354f93a4042d3debdca5e1 = new Entity("Cube Entity")
engine.addEntity(cubeEntity_624a0f83cd354f93a4042d3debdca5e1)
const cubeEntity_624a0f83cd354f93a4042d3debdca5e1_transform = new Transform({
  position: new Vector3(17.75, 1.5, 16.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.25, 3, 10)
})
cubeEntity_624a0f83cd354f93a4042d3debdca5e1.addComponentOrReplace(cubeEntity_624a0f83cd354f93a4042d3debdca5e1_transform)
const cubeEntity_624a0f83cd354f93a4042d3debdca5e1_boxShape = new BoxShape()
cubeEntity_624a0f83cd354f93a4042d3debdca5e1.addComponentOrReplace(cubeEntity_624a0f83cd354f93a4042d3debdca5e1_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity_156b86292b6f4e88a928923522fdd092 = new Entity("Cube Entity")
engine.addEntity(cubeEntity_156b86292b6f4e88a928923522fdd092)
const cubeEntity_156b86292b6f4e88a928923522fdd092_transform = new Transform({
  position: new Vector3(12.75, 1.5, 21.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(0.25, 3, 10)
})
cubeEntity_156b86292b6f4e88a928923522fdd092.addComponentOrReplace(cubeEntity_156b86292b6f4e88a928923522fdd092_transform)
const cubeEntity_156b86292b6f4e88a928923522fdd092_boxShape = new BoxShape()
cubeEntity_156b86292b6f4e88a928923522fdd092.addComponentOrReplace(cubeEntity_156b86292b6f4e88a928923522fdd092_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity_0b27dba341604dc3b3818c45d20a5a97 = new Entity("Cube Entity")
engine.addEntity(cubeEntity_0b27dba341604dc3b3818c45d20a5a97)
const cubeEntity_0b27dba341604dc3b3818c45d20a5a97_transform = new Transform({
  position: new Vector3(12.75, 1.5, 11.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(0.25, 3, 10)
})
cubeEntity_0b27dba341604dc3b3818c45d20a5a97.addComponentOrReplace(cubeEntity_0b27dba341604dc3b3818c45d20a5a97_transform)
const cubeEntity_0b27dba341604dc3b3818c45d20a5a97_boxShape = new BoxShape()
cubeEntity_0b27dba341604dc3b3818c45d20a5a97.addComponentOrReplace(cubeEntity_0b27dba341604dc3b3818c45d20a5a97_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity_4fd5d9ec1bf64b01bf0c2ed57d525eca = new Entity("Cube Entity")
engine.addEntity(cubeEntity_4fd5d9ec1bf64b01bf0c2ed57d525eca)
const cubeEntity_4fd5d9ec1bf64b01bf0c2ed57d525eca_transform = new Transform({
  position: new Vector3(7.745, 1.5, 13.41789),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.25, 3, 4.5)
})
cubeEntity_4fd5d9ec1bf64b01bf0c2ed57d525eca.addComponentOrReplace(cubeEntity_4fd5d9ec1bf64b01bf0c2ed57d525eca_transform)
const cubeEntity_4fd5d9ec1bf64b01bf0c2ed57d525eca_boxShape = new BoxShape()
cubeEntity_4fd5d9ec1bf64b01bf0c2ed57d525eca.addComponentOrReplace(cubeEntity_4fd5d9ec1bf64b01bf0c2ed57d525eca_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804 = new Entity("Door Marco Normal")
engine.addEntity(doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804)
const doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804_transform = new Transform({
  position: new Vector3(7.75, -0.59427, 15.75),
  rotation: new Quaternion(0, 0.7071065, 0, 0.7071071),
  scale: new Vector3(1, 1, 1)
})
doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804.addComponentOrReplace(doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804_transform)
const doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804_GLTFShape = new GLTFShape("assets/models/dfee69da-8c9d-4538-af25-283601af6455/Door Marco Normal.glb")
doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804_GLTFShape.withCollisions = true
doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804_GLTFShape.isPointerBlocker = true
doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804_GLTFShape.visible = true
doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804.addComponentOrReplace(doorMarcoNormal_3ffbe66f94ad420cb522c39323a75804_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity_2795e9ecb1cc44f3a20e2bc0ee246363 = new Entity("Cube Entity")
engine.addEntity(cubeEntity_2795e9ecb1cc44f3a20e2bc0ee246363)
const cubeEntity_2795e9ecb1cc44f3a20e2bc0ee246363_transform = new Transform({
  position: new Vector3(7.745, 1.5, 19.08814),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.25, 3, 4.5)
})
cubeEntity_2795e9ecb1cc44f3a20e2bc0ee246363.addComponentOrReplace(cubeEntity_2795e9ecb1cc44f3a20e2bc0ee246363_transform)
const cubeEntity_2795e9ecb1cc44f3a20e2bc0ee246363_boxShape = new BoxShape()
cubeEntity_2795e9ecb1cc44f3a20e2bc0ee246363.addComponentOrReplace(cubeEntity_2795e9ecb1cc44f3a20e2bc0ee246363_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity_e60d2131f498455b9ce404b6128026c8 = new Entity("Cube Entity")
engine.addEntity(cubeEntity_e60d2131f498455b9ce404b6128026c8)
const cubeEntity_e60d2131f498455b9ce404b6128026c8_transform = new Transform({
  position: new Vector3(7.745, 2.718903, 16.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.25, 0.5657597, 1.25)
})
cubeEntity_e60d2131f498455b9ce404b6128026c8.addComponentOrReplace(cubeEntity_e60d2131f498455b9ce404b6128026c8_transform)
const cubeEntity_e60d2131f498455b9ce404b6128026c8_boxShape = new BoxShape()
cubeEntity_e60d2131f498455b9ce404b6128026c8.addComponentOrReplace(cubeEntity_e60d2131f498455b9ce404b6128026c8_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const door_7b31e6b8a9064403ae9e6e19889993d7 = new Entity("Door")
engine.addEntity(door_7b31e6b8a9064403ae9e6e19889993d7)
const door_7b31e6b8a9064403ae9e6e19889993d7_transform = new Transform({
  position: new Vector3(7.75, -0.594, 15.75),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
door_7b31e6b8a9064403ae9e6e19889993d7.addComponentOrReplace(door_7b31e6b8a9064403ae9e6e19889993d7_transform)
const door_7b31e6b8a9064403ae9e6e19889993d7_GLTFShape = new GLTFShape("assets/models/44083cd0-e386-4bf3-8f8b-c823cacf9cd0/Door 7.glb")
door_7b31e6b8a9064403ae9e6e19889993d7_GLTFShape.withCollisions = true
door_7b31e6b8a9064403ae9e6e19889993d7_GLTFShape.isPointerBlocker = true
door_7b31e6b8a9064403ae9e6e19889993d7_GLTFShape.visible = true
door_7b31e6b8a9064403ae9e6e19889993d7.addComponentOrReplace(door_7b31e6b8a9064403ae9e6e19889993d7_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity_cec9cf62b9034061b1adc332c4a6c08f = new Entity("Cube Entity")
engine.addEntity(cubeEntity_cec9cf62b9034061b1adc332c4a6c08f)
const cubeEntity_cec9cf62b9034061b1adc332c4a6c08f_transform = new Transform({
  position: new Vector3(11.5, 3.25, 16.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(7.25, 0.585, 10)
})
cubeEntity_cec9cf62b9034061b1adc332c4a6c08f.addComponentOrReplace(cubeEntity_cec9cf62b9034061b1adc332c4a6c08f_transform)
const cubeEntity_cec9cf62b9034061b1adc332c4a6c08f_boxShape = new BoxShape()
cubeEntity_cec9cf62b9034061b1adc332c4a6c08f.addComponentOrReplace(cubeEntity_cec9cf62b9034061b1adc332c4a6c08f_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity_9521270100514c64ad486673790efa50 = new Entity("Cube Entity")
engine.addEntity(cubeEntity_9521270100514c64ad486673790efa50)
const cubeEntity_9521270100514c64ad486673790efa50_transform = new Transform({
  position: new Vector3(16.46, 3.25, 17.356),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.683, 0.586, 7.75)
})
cubeEntity_9521270100514c64ad486673790efa50.addComponentOrReplace(cubeEntity_9521270100514c64ad486673790efa50_transform)
const cubeEntity_9521270100514c64ad486673790efa50_boxShape = new BoxShape()
cubeEntity_9521270100514c64ad486673790efa50.addComponentOrReplace(cubeEntity_9521270100514c64ad486673790efa50_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const elevator_fafe07d4605e499994691d7aabecf299 = new Entity("Elevator")
engine.addEntity(elevator_fafe07d4605e499994691d7aabecf299)
const elevator_fafe07d4605e499994691d7aabecf299_transform = new Transform({
  position: new Vector3(16.347, 0, 12.429),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.113, 0.25, 1.75)
})
elevator_fafe07d4605e499994691d7aabecf299.addComponentOrReplace(elevator_fafe07d4605e499994691d7aabecf299_transform)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const elevatortarget_e1ecde70fe184ac488cb91478ac9d1d2 = new Entity("ElevatorTarget")
engine.addEntity(elevatortarget_e1ecde70fe184ac488cb91478ac9d1d2)
const elevatortarget_e1ecde70fe184ac488cb91478ac9d1d2_transform = new Transform({
  position: new Vector3(0, 13, 0),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 0.9999999)
})
elevatortarget_e1ecde70fe184ac488cb91478ac9d1d2.addComponentOrReplace(elevatortarget_e1ecde70fe184ac488cb91478ac9d1d2_transform)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66 = new Entity("ElevatorPlatform")
engine.addEntity(elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66)
const elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66_transform = new Transform({
  position: new Vector3(0, 0, 0),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.111, 1.067, 0.975)
})
elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66.addComponentOrReplace(elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66_transform)
const elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66_boxShape = new BoxShape()
elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66.addComponentOrReplace(elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const elevator_bd066ce6bcca473980c5781dc6da0621 = new Entity("Elevator")
engine.addEntity(elevator_bd066ce6bcca473980c5781dc6da0621)
const elevator_bd066ce6bcca473980c5781dc6da0621_transform = new Transform({
  position: new Vector3(9.597, 3.5, 19.679),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.113, 0.25, 1.75)
})
elevator_bd066ce6bcca473980c5781dc6da0621.addComponentOrReplace(elevator_bd066ce6bcca473980c5781dc6da0621_transform)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const elevatorplatform2_be0a2dcde3384dccb9579816809bd276 = new Entity("ElevatorPlatform2")
engine.addEntity(elevatorplatform2_be0a2dcde3384dccb9579816809bd276)
const elevatorplatform2_be0a2dcde3384dccb9579816809bd276_transform = new Transform({
  position: new Vector3(-0.042, 0, 0.041),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.111, 1.067, 0.975)
})
elevatorplatform2_be0a2dcde3384dccb9579816809bd276.addComponentOrReplace(elevatorplatform2_be0a2dcde3384dccb9579816809bd276_transform)
const elevatorplatform2_be0a2dcde3384dccb9579816809bd276_boxShape = new BoxShape()
elevatorplatform2_be0a2dcde3384dccb9579816809bd276.addComponentOrReplace(elevatorplatform2_be0a2dcde3384dccb9579816809bd276_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const elevatortarget2_bd2254250f69462d95f9bf56abf7bfff = new Entity("ElevatorTarget2")
engine.addEntity(elevatortarget2_bd2254250f69462d95f9bf56abf7bfff)
const elevatortarget2_bd2254250f69462d95f9bf56abf7bfff_transform = new Transform({
  position: new Vector3(0, 35, 0),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
elevatortarget2_bd2254250f69462d95f9bf56abf7bfff.addComponentOrReplace(elevatortarget2_bd2254250f69462d95f9bf56abf7bfff_transform)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

constructionCone01_51992f1bdb4d4330b779229281a8ecba.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionSign01_c89e62cf50de4a7daa56695c46877c70.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionFence01_61a8d02b76914237b9f68254ba07ff2a.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionFence01_d395dc5ade504db8bcdec9c5f94e7166.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionCone01_9934600b25754a92a1d38ba1d3dc3386.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionFence01_d4a8387efdb6472483543df8dfbb092b.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionFence01_95a6c3c57ca04fd38c1da67c4cd4e247.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionFence01_262d328e8cd7437c99bfc1f825482e64.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionFence01_e3b5a4cc484a4eb380ab6d0eae30c55f.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionCone01_baac1c63b2864256ae7214e96b2ac1d8.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionLadder01_707ba14ce5c34c65b6b49a182563223f.setParent(construction_426309a2e66647e4a1772df96632f90b)
constructionCone01_2baadfe09cac4f1d9349b272343af786.setParent(construction_426309a2e66647e4a1772df96632f90b)
elevatortarget_e1ecde70fe184ac488cb91478ac9d1d2.setParent(elevator_fafe07d4605e499994691d7aabecf299)
elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66.setParent(elevator_fafe07d4605e499994691d7aabecf299)
elevatorplatform2_be0a2dcde3384dccb9579816809bd276.setParent(elevator_bd066ce6bcca473980c5781dc6da0621)
elevatortarget2_bd2254250f69462d95f9bf56abf7bfff.setParent(elevator_bd066ce6bcca473980c5781dc6da0621)



export let scene = {
  door:{
    entity: door_7b31e6b8a9064403ae9e6e19889993d7,
    transform: door_7b31e6b8a9064403ae9e6e19889993d7_transform,
    GLTFShape: door_7b31e6b8a9064403ae9e6e19889993d7_GLTFShape,
  },
  elevatortarget:{
    entity: elevatortarget_e1ecde70fe184ac488cb91478ac9d1d2,
    transform: elevatortarget_e1ecde70fe184ac488cb91478ac9d1d2_transform,
  },
  elevatorplatform:{
    entity: elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66,
    transform: elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66_transform,
    boxShape: elevatorplatform_1a4ef92f17cc45c29b0ec7af18e42b66_boxShape,
  },
  elevatorplatform2:{
    entity: elevatorplatform2_be0a2dcde3384dccb9579816809bd276,
    transform: elevatorplatform2_be0a2dcde3384dccb9579816809bd276_transform,
    boxShape: elevatorplatform2_be0a2dcde3384dccb9579816809bd276_boxShape,
  },
  elevatortarget2:{
    entity: elevatortarget2_bd2254250f69462d95f9bf56abf7bfff,
    transform: elevatortarget2_bd2254250f69462d95f9bf56abf7bfff_transform,
  },
}

