// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const goal_66e83169166f4af689cf68383958b3a8 = new Entity("Goal")
engine.addEntity(goal_66e83169166f4af689cf68383958b3a8)
const goal_66e83169166f4af689cf68383958b3a8_transform = new Transform({
  position: new Vector3(16.75, 7.25, 32.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(10.5, 1, 10.75)
})
goal_66e83169166f4af689cf68383958b3a8.addComponentOrReplace(goal_66e83169166f4af689cf68383958b3a8_transform)
const goal_66e83169166f4af689cf68383958b3a8_boxShape = new BoxShape()
goal_66e83169166f4af689cf68383958b3a8.addComponentOrReplace(goal_66e83169166f4af689cf68383958b3a8_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platform_0133b9eefdc44018ac07184fec2e2181 = new Entity("Platform")
engine.addEntity(platform_0133b9eefdc44018ac07184fec2e2181)
const platform_0133b9eefdc44018ac07184fec2e2181_transform = new Transform({
  position: new Vector3(7, 1, 2.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.25, 0.25, 2.5)
})
platform_0133b9eefdc44018ac07184fec2e2181.addComponentOrReplace(platform_0133b9eefdc44018ac07184fec2e2181_transform)
const platform_0133b9eefdc44018ac07184fec2e2181_boxShape = new BoxShape()
platform_0133b9eefdc44018ac07184fec2e2181.addComponentOrReplace(platform_0133b9eefdc44018ac07184fec2e2181_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformDisp1_d9200f20fa3f493da20e38c2c0f33333 = new Entity("Platform Disp 1")
engine.addEntity(platformDisp1_d9200f20fa3f493da20e38c2c0f33333)
const platformDisp1_d9200f20fa3f493da20e38c2c0f33333_transform = new Transform({
  position: new Vector3(7, 2, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.25, 0.25, 2.5)
})
platformDisp1_d9200f20fa3f493da20e38c2c0f33333.addComponentOrReplace(platformDisp1_d9200f20fa3f493da20e38c2c0f33333_transform)
const platformDisp1_d9200f20fa3f493da20e38c2c0f33333_boxShape = new BoxShape()
platformDisp1_d9200f20fa3f493da20e38c2c0f33333.addComponentOrReplace(platformDisp1_d9200f20fa3f493da20e38c2c0f33333_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platform_7ec83883ede74e43b9b33c00537992aa = new Entity("Platform")
engine.addEntity(platform_7ec83883ede74e43b9b33c00537992aa)
const platform_7ec83883ede74e43b9b33c00537992aa_transform = new Transform({
  position: new Vector3(12.25, 2.75, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.25, 0.25, 2.5)
})
platform_7ec83883ede74e43b9b33c00537992aa.addComponentOrReplace(platform_7ec83883ede74e43b9b33c00537992aa_transform)
const platform_7ec83883ede74e43b9b33c00537992aa_boxShape = new BoxShape()
platform_7ec83883ede74e43b9b33c00537992aa.addComponentOrReplace(platform_7ec83883ede74e43b9b33c00537992aa_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platform_ed29d7bb6f5d4ebd92f27ec64b8bce56 = new Entity("Platform")
engine.addEntity(platform_ed29d7bb6f5d4ebd92f27ec64b8bce56)
const platform_ed29d7bb6f5d4ebd92f27ec64b8bce56_transform = new Transform({
  position: new Vector3(14.25, 3.75, 12.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.25, 0.25, 2.5)
})
platform_ed29d7bb6f5d4ebd92f27ec64b8bce56.addComponentOrReplace(platform_ed29d7bb6f5d4ebd92f27ec64b8bce56_transform)
const platform_ed29d7bb6f5d4ebd92f27ec64b8bce56_boxShape = new BoxShape()
platform_ed29d7bb6f5d4ebd92f27ec64b8bce56.addComponentOrReplace(platform_ed29d7bb6f5d4ebd92f27ec64b8bce56_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470 = new Entity("Platform Disp 2")
engine.addEntity(platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470)
const platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470_transform = new Transform({
  position: new Vector3(19.5, 4.5, 12.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.25, 0.25, 2.5)
})
platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470.addComponentOrReplace(platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470_transform)
const platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470_boxShape = new BoxShape()
platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470.addComponentOrReplace(platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df = new Entity("Platform Disp 3")
engine.addEntity(platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df)
const platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df_transform = new Transform({
  position: new Vector3(22.25, 5.25, 17),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.25, 0.25, 2.5)
})
platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df.addComponentOrReplace(platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df_transform)
const platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df_boxShape = new BoxShape()
platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df.addComponentOrReplace(platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platform_edfeb50eb71145fb85afd2b46935f6d7 = new Entity("Platform")
engine.addEntity(platform_edfeb50eb71145fb85afd2b46935f6d7)
const platform_edfeb50eb71145fb85afd2b46935f6d7_transform = new Transform({
  position: new Vector3(16, 6.5, 25.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.25, 0.25, 2.5)
})
platform_edfeb50eb71145fb85afd2b46935f6d7.addComponentOrReplace(platform_edfeb50eb71145fb85afd2b46935f6d7_transform)
const platform_edfeb50eb71145fb85afd2b46935f6d7_boxShape = new BoxShape()
platform_edfeb50eb71145fb85afd2b46935f6d7.addComponentOrReplace(platform_edfeb50eb71145fb85afd2b46935f6d7_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformDisp4_1839decaa26f4219a52dab25c404531c = new Entity("Platform Disp 4")
engine.addEntity(platformDisp4_1839decaa26f4219a52dab25c404531c)
const platformDisp4_1839decaa26f4219a52dab25c404531c_transform = new Transform({
  position: new Vector3(20, 5.75, 20.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.25, 0.25, 2.5)
})
platformDisp4_1839decaa26f4219a52dab25c404531c.addComponentOrReplace(platformDisp4_1839decaa26f4219a52dab25c404531c_transform)
const platformDisp4_1839decaa26f4219a52dab25c404531c_boxShape = new BoxShape()
platformDisp4_1839decaa26f4219a52dab25c404531c.addComponentOrReplace(platformDisp4_1839decaa26f4219a52dab25c404531c_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const imageScreen_76359d87561748fcb3ea8736f411d01a = new Entity("Image Screen")
engine.addEntity(imageScreen_76359d87561748fcb3ea8736f411d01a)
const imageScreen_76359d87561748fcb3ea8736f411d01a_transform = new Transform({
  position: new Vector3(14.25, 1.5, 37.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3.988, 2.24, 0.246)
})
imageScreen_76359d87561748fcb3ea8736f411d01a.addComponentOrReplace(imageScreen_76359d87561748fcb3ea8736f411d01a_transform)
const imageScreen_76359d87561748fcb3ea8736f411d01a_planeShape = new PlaneShape()
imageScreen_76359d87561748fcb3ea8736f411d01a.addComponentOrReplace(imageScreen_76359d87561748fcb3ea8736f411d01a_planeShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const videosScreen_11949933690143e2ad324e268ab7f992 = new Entity("videos Screen")
engine.addEntity(videosScreen_11949933690143e2ad324e268ab7f992)
const videosScreen_11949933690143e2ad324e268ab7f992_transform = new Transform({
  position: new Vector3(18.75, 1.5, 37.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3.988, 2.24, 0.246)
})
videosScreen_11949933690143e2ad324e268ab7f992.addComponentOrReplace(videosScreen_11949933690143e2ad324e268ab7f992_transform)
const videosScreen_11949933690143e2ad324e268ab7f992_planeShape = new PlaneShape()
videosScreen_11949933690143e2ad324e268ab7f992.addComponentOrReplace(videosScreen_11949933690143e2ad324e268ab7f992_planeShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const temperatureText_f40339150590473288c3034d05b5c05d = new Entity("temperature Text")
engine.addEntity(temperatureText_f40339150590473288c3034d05b5c05d)
const temperatureText_f40339150590473288c3034d05b5c05d_transform = new Transform({
  position: new Vector3(16.5, 3.25, 37.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
temperatureText_f40339150590473288c3034d05b5c05d.addComponentOrReplace(temperatureText_f40339150590473288c3034d05b5c05d_transform)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
  platformDisp1:{
    entity: platformDisp1_d9200f20fa3f493da20e38c2c0f33333,
    transform: platformDisp1_d9200f20fa3f493da20e38c2c0f33333_transform,
    boxShape: platformDisp1_d9200f20fa3f493da20e38c2c0f33333_boxShape,
  },
  platformDisp2:{
    entity: platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470,
    transform: platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470_transform,
    boxShape: platformDisp2_5cb3de493ba246dcb6cb2f2e9383d470_boxShape,
  },
  platformDisp3:{
    entity: platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df,
    transform: platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df_transform,
    boxShape: platformDisp3_e497d8fedab0480ea6e6f9b7b96e28df_boxShape,
  },
  platformDisp4:{
    entity: platformDisp4_1839decaa26f4219a52dab25c404531c,
    transform: platformDisp4_1839decaa26f4219a52dab25c404531c_transform,
    boxShape: platformDisp4_1839decaa26f4219a52dab25c404531c_boxShape,
  },
  imageScreen:{
    entity: imageScreen_76359d87561748fcb3ea8736f411d01a,
    transform: imageScreen_76359d87561748fcb3ea8736f411d01a_transform,
    planeShape: imageScreen_76359d87561748fcb3ea8736f411d01a_planeShape,
  },
  videosScreen:{
    entity: videosScreen_11949933690143e2ad324e268ab7f992,
    transform: videosScreen_11949933690143e2ad324e268ab7f992_transform,
    planeShape: videosScreen_11949933690143e2ad324e268ab7f992_planeShape,
  },
  temperatureText:{
    entity: temperatureText_f40339150590473288c3034d05b5c05d,
    transform: temperatureText_f40339150590473288c3034d05b5c05d_transform,
  },
}

