// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity12 = new Entity("Cube Entity")
engine.addEntity(cubeEntity12)
const cubeEntity12transform = new Transform({
  position: new Vector3(13.25, 2.25, 4.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.75, 1, 1.75)
})
cubeEntity12.addComponentOrReplace(cubeEntity12transform)
const cubeEntity12GLTFShape = new GLTFShape("assets/models/c6075674-d365-4bf1-bb5e-4f40038d8a14/DocksModuleSmall_01/DocksModuleSmall_01.glb")
cubeEntity12GLTFShape.withCollisions = true
cubeEntity12GLTFShape.isPointerBlocker = true
cubeEntity12GLTFShape.visible = true
cubeEntity12.addComponentOrReplace(cubeEntity12GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity15 = new Entity("Cube Entity")
engine.addEntity(cubeEntity15)
const cubeEntity15transform = new Transform({
  position: new Vector3(10, -0.25, 6),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 2, 2)
})
cubeEntity15.addComponentOrReplace(cubeEntity15transform)
const cubeEntity15GLTFShape = new GLTFShape("assets/models/8f2069c1-ab16-4b16-b2cb-f2cc9238917e/FenceWoodLarge_01/FenceWoodLarge_01.glb")
cubeEntity15GLTFShape.withCollisions = true
cubeEntity15GLTFShape.isPointerBlocker = true
cubeEntity15GLTFShape.visible = true
cubeEntity15.addComponentOrReplace(cubeEntity15GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const docksModuleStairs0117 = new Entity("Docks Module Stairs 01")
engine.addEntity(docksModuleStairs0117)
const docksModuleStairs0117transform = new Transform({
  position: new Vector3(2.25, -0.25, 2.75),
  rotation: new Quaternion(0, -0.7071066, 0, 0.7071071),
  scale: new Vector3(1, 1.24934, 1)
})
docksModuleStairs0117.addComponentOrReplace(docksModuleStairs0117transform)
const docksModuleStairs0117GLTFShape = new GLTFShape("assets/models/fdb0f713-5c34-4f5a-811b-8c4417b5ffd5/DocksModuleStairs_01/DocksModuleStairs_01.glb")
docksModuleStairs0117GLTFShape.withCollisions = true
docksModuleStairs0117GLTFShape.isPointerBlocker = true
docksModuleStairs0117GLTFShape.visible = true
docksModuleStairs0117.addComponentOrReplace(docksModuleStairs0117GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const docksModuleStairs0118 = new Entity("Docks Module Stairs 01")
engine.addEntity(docksModuleStairs0118)
const docksModuleStairs0118transform = new Transform({
  position: new Vector3(4.220111, 0.677565, 2.75),
  rotation: new Quaternion(0, -0.7071066, 0, 0.7071071),
  scale: new Vector3(1, 1.24934, 1)
})
docksModuleStairs0118.addComponentOrReplace(docksModuleStairs0118transform)
docksModuleStairs0118.addComponentOrReplace(docksModuleStairs0117GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const docksModuleStairs0119 = new Entity("Docks Module Stairs 01")
engine.addEntity(docksModuleStairs0119)
const docksModuleStairs0119transform = new Transform({
  position: new Vector3(6.122581, 1.592024, 2.75),
  rotation: new Quaternion(0, -0.7071066, 0, 0.7071071),
  scale: new Vector3(1, 1.24934, 1)
})
docksModuleStairs0119.addComponentOrReplace(docksModuleStairs0119transform)
docksModuleStairs0119.addComponentOrReplace(docksModuleStairs0117GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0120 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0120)
const fenceSticksEnd0120transform = new Transform({
  position: new Vector3(12.23, 0, 1.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0120.addComponentOrReplace(fenceSticksEnd0120transform)
const fenceSticksEnd0120GLTFShape = new GLTFShape("assets/models/1766c251-9c6e-41f4-9141-7ffcfb73a612/FenceSticksEnd_01/FenceSticksEnd_01.glb")
fenceSticksEnd0120GLTFShape.withCollisions = true
fenceSticksEnd0120GLTFShape.isPointerBlocker = true
fenceSticksEnd0120GLTFShape.visible = true
fenceSticksEnd0120.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0121 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0121)
const fenceSticksEnd0121transform = new Transform({
  position: new Vector3(14.372, 0, 1.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0121.addComponentOrReplace(fenceSticksEnd0121transform)
fenceSticksEnd0121.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0122 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0122)
const fenceSticksEnd0122transform = new Transform({
  position: new Vector3(14.655, 0, 4.192257),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0122.addComponentOrReplace(fenceSticksEnd0122transform)
fenceSticksEnd0122.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0123 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0123)
const fenceSticksEnd0123transform = new Transform({
  position: new Vector3(11.824, 0, 4.226),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0123.addComponentOrReplace(fenceSticksEnd0123transform)
fenceSticksEnd0123.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0124 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0124)
const fenceSticksEnd0124transform = new Transform({
  position: new Vector3(14.372, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0124.addComponentOrReplace(fenceSticksEnd0124transform)
fenceSticksEnd0124.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity25 = new Entity("Cube Entity")
engine.addEntity(cubeEntity25)
const cubeEntity25transform = new Transform({
  position: new Vector3(13.25, 2.25, 11.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.75, 1, 1.75)
})
cubeEntity25.addComponentOrReplace(cubeEntity25transform)
cubeEntity25.addComponentOrReplace(cubeEntity12GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0126 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0126)
const fenceSticksEnd0126transform = new Transform({
  position: new Vector3(12.23, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0126.addComponentOrReplace(fenceSticksEnd0126transform)
fenceSticksEnd0126.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0127 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0127)
const fenceSticksEnd0127transform = new Transform({
  position: new Vector3(14.655, 0, 10.69226),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0127.addComponentOrReplace(fenceSticksEnd0127transform)
fenceSticksEnd0127.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0128 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0128)
const fenceSticksEnd0128transform = new Transform({
  position: new Vector3(11.824, 0, 10.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0128.addComponentOrReplace(fenceSticksEnd0128transform)
fenceSticksEnd0128.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity29 = new Entity("Cube Entity")
engine.addEntity(cubeEntity29)
const cubeEntity29transform = new Transform({
  position: new Vector3(6.5, 2.25, 11.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.75, 1, 1.75)
})
cubeEntity29.addComponentOrReplace(cubeEntity29transform)
cubeEntity29.addComponentOrReplace(cubeEntity12GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0130 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0130)
const fenceSticksEnd0130transform = new Transform({
  position: new Vector3(7.905, 0, 10.69226),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0130.addComponentOrReplace(fenceSticksEnd0130transform)
fenceSticksEnd0130.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0131 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0131)
const fenceSticksEnd0131transform = new Transform({
  position: new Vector3(5.074, 0, 10.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0131.addComponentOrReplace(fenceSticksEnd0131transform)
fenceSticksEnd0131.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0132 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0132)
const fenceSticksEnd0132transform = new Transform({
  position: new Vector3(5.48, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0132.addComponentOrReplace(fenceSticksEnd0132transform)
fenceSticksEnd0132.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceSticksEnd0133 = new Entity("Fence Sticks End 01")
engine.addEntity(fenceSticksEnd0133)
const fenceSticksEnd0133transform = new Transform({
  position: new Vector3(7.5, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 3)
})
fenceSticksEnd0133.addComponentOrReplace(fenceSticksEnd0133transform)
fenceSticksEnd0133.addComponentOrReplace(fenceSticksEnd0120GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity34 = new Entity("Cube Entity")
engine.addEntity(cubeEntity34)
const cubeEntity34transform = new Transform({
  position: new Vector3(10, 3.5, 6),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 2, 2)
})
cubeEntity34.addComponentOrReplace(cubeEntity34transform)
cubeEntity34.addComponentOrReplace(cubeEntity15GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cubeEntity35 = new Entity("Cube Entity")
engine.addEntity(cubeEntity35)
const cubeEntity35transform = new Transform({
  position: new Vector3(10, 7, 6),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 2, 2)
})
cubeEntity35.addComponentOrReplace(cubeEntity35transform)
cubeEntity35.addComponentOrReplace(cubeEntity15GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0136 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0136)
const floorBaseGrass0136transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0136.addComponentOrReplace(floorBaseGrass0136transform)
const floorBaseGrass0136GLTFShape = new GLTFShape("assets/models/c9b17021-765c-4d9a-9966-ce93a9c323d1/FloorBaseGrass_01/FloorBaseGrass_01.glb")
floorBaseGrass0136GLTFShape.withCollisions = true
floorBaseGrass0136GLTFShape.isPointerBlocker = true
floorBaseGrass0136GLTFShape.visible = true
floorBaseGrass0136.addComponentOrReplace(floorBaseGrass0136GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const raft0137 = new Entity("Raft 01")
engine.addEntity(raft0137)
const raft0137transform = new Transform({
  position: new Vector3(3, 0, 12),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
raft0137.addComponentOrReplace(raft0137transform)
const raft0137GLTFShape = new GLTFShape("assets/models/5d6202b7-d5b7-4bc6-a4a2-c1e6b35c0bb6/Raft_01/Raft_01.glb")
raft0137GLTFShape.withCollisions = true
raft0137GLTFShape.isPointerBlocker = true
raft0137GLTFShape.visible = true
raft0137.addComponentOrReplace(raft0137GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const button39 = new Entity("Button")
engine.addEntity(button39)
const button39transform = new Transform({
  position: new Vector3(8.5, 0, 11.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
button39.addComponentOrReplace(button39transform)
const button39GLTFShape = new GLTFShape("assets/models/f25b55b3-3260-4d81-b8e5-a2654ac9a3f5/Cannon_01/Cannon_01.glb")
button39GLTFShape.withCollisions = true
button39GLTFShape.isPointerBlocker = true
button39GLTFShape.visible = true
button39.addComponentOrReplace(button39GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const doorPivot40 = new Entity("Door Pivot")
engine.addEntity(doorPivot40)
const doorPivot40transform = new Transform({
  position: new Vector3(11, 0, 15.25),
  rotation: new Quaternion(0, 4.470348E-08, 0, 1),
  scale: new Vector3(1, 1, 1)
})
doorPivot40.addComponentOrReplace(doorPivot40transform)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const door38 = new Entity("Door")
engine.addEntity(door38)
const door38transform = new Transform({
  position: new Vector3(0, 0, -1.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.207, 0.75, 0.5)
})
door38.addComponentOrReplace(door38transform)
const door38GLTFShape = new GLTFShape("assets/models/3ae1efaa-e0a7-47dd-ab64-aedf572f658c/RockBig_04/RockBig_04.glb")
door38GLTFShape.withCollisions = true
door38GLTFShape.isPointerBlocker = true
door38GLTFShape.visible = true
door38.addComponentOrReplace(door38GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

door38.setParent(doorPivot40)



export let scene = {
  raft01:{
    entity: raft0137,
    transform: raft0137transform,
    GLTFShape: raft0137GLTFShape,
  },
  button:{
    entity: button39,
    transform: button39transform,
    GLTFShape: button39GLTFShape,
  },
  doorPivot:{
    entity: doorPivot40,
    transform: doorPivot40transform,
  },
  door:{
    entity: door38,
    transform: door38transform,
    GLTFShape: door38GLTFShape,
  },
}

